### ISSUE TITLE
Compiling assistance on freebsd

### ISSUE THREAD

**Issue by jungle-boogie** [sordina/SQLBong#5]
Hello,

Really looking forward to using your tool, but it looks like there are issues comping for me. Would you be able to provide any guidance?

`cc -v
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.2
Thread model: posix
Selected GCC installation: `

    % make
    echo "#ifndef USAGEH"                                                             > usage.h
    echo "#define USAGEH"                                                            >> usage.h
    echo "void usage() {"                                                            >> usage.h
    cat README.md | sed 's/["%\\]/\\&/g;s/^/printf("/;s/$/\\n");/' | grep -v '<img' >> usage.h
    echo "}"                                                                         >> usage.h
    echo "#endif"                                                                    >> usage.h
    clang -lm -Wall pcre_split.c sqlbong.c -lpcre -lsqlite3 -o sqlbong
    clang: error: no such file or directory: 'pcre_split.c'
    *** Error code 1

    Stop.
    make: stopped in /usr/home/jungle/bin/SQLBong

**Comment by sordina** [comment]
Hi jungle-boogie,

The pcre* files are meant to be symlinks to the files in pcre_split/{src,inc}/*.

It looks like these links aren't working correctly for you. If you copy the .c and .h files to the project root it should compile okay.

Let me know how it goes :)

**Comment by sordina** [comment]
Ah actually the pcre_split folder is a Git submodule, so ensure that your submodules are checked out with the following commands:

	git submodule init
	git submodule update

Hopefully this will fix your symlinks and let you compile.

**Comment by jungle-boogie** [comment]
Hi sordina,

Got a little further but still died:

echo "#ifndef USAGEH"                                                             > usage.h
echo "#define USAGEH"                                                            >> usage.h
echo "void usage() {"                                                            >> usage.h
cat README.md | sed 's/["%\\]/\\&/g;s/^/printf("/;s/$/\\n");/' | grep -v '<img' >> usage.h
echo "}"                                                                         >> usage.h
echo "#endif"                                                                    >> usage.h
clang -lm -Wall pcre_split.c sqlbong.c -lpcre -lsqlite3 -o sqlbong
In file included from pcre_split.c:1:
./pcre_split.h:9:10: fatal error: 'pcre.h' file not found
#include <pcre.h>
         ^
1 error generated.
sqlbong.c:2:10: fatal error: 'sqlite3.h' file not found
#include <sqlite3.h>
         ^
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/jungle/bin/SQLBong

Output from running your two git commands:
`lrwxr-xr-x  1 jungle  jungle      27 Aug 19 06:15 pcre_split.c -> pcre_split/src/pcre_split.c`
`lrwxr-xr-x  1 jungle  jungle      27 Aug 19 06:15 pcre_split.h -> pcre_split/inc/pcre_split.h`

**Comment by sordina** [comment]
You'll need to install the pcre and sqlite3 libraries before you can compile the project. I'm not familiar with how to do this on FreeBSD, but it should be fairly straightforward. If you are still having issues with this aspect I'll ask my friend who runs FreeBSD to step through the compilation with me.

**Comment by jungle-boogie** [comment]
Hello,

pcre is installed and I install sqlite3 from source.

pcre.h is here: `/usr/local/include/pcre.h`
sqlite3.h is here: `/usr/local/include/sqlite3.h`

Thanks!

**Comment by jungle-boogie** [comment]
Hello,

If you use vagrant, you can easily obtain freebsd here:
https://atlas.hashicorp.com/freebsd/boxes/FreeBSD-10.2-RELEASE

Thanks!

**Comment by sordina** [comment]
Cheers, I'll see if I can have a look into this tonight.

In the mean-time, you may be able to point to the libraries directly, e.g.

    -L/usr/local/include/pcre.h

instead of

    -lpcre

Worth a short!

**Comment by jungle-boogie** [comment]
Hello,

Sorry, I don't know how to point it directly with what you said. Are you suggesting modify `pcre_split/inc/pcre_split.h` and modify the #include?

**Comment by sordina** [comment]
I'm not sure that you need to change the include... You should be able to point to the library on your local box, e.g. I compiled with:


    lyndon@endpin ! master ✖ ~/Documents/Code/SQLBong clang -lm -Wall pcre_split.c sqlbong.c /usr/local/lib/libpcre.a /usr/pkg/lib/libsqlite3.a -o sqlbong
    lyndon@endpin ! master ✖ ~/Documents/Code/SQLBong ./sqlbong
    Usage: ./sqlbong [-h] [-f <output_database>] [-d <regex_delimiter>] <sql>*

**Comment by jungle-boogie** [comment]
Hello,

No, not any better.

    % clang -lm -Wall pcre_split.c sqlbong.c /usr/local/lib/libpcre.a /usr/local/lib/libsqlite3.a -o sqlbong
    In file included from pcre_split.c:1:
    ./pcre_split.h:9:10: fatal error: 'pcre.h' file not found
    #include <pcre.h>
         ^
    1 error generated.
    sqlbong.c:2:10: fatal error: 'sqlite3.h' file not found
    #include <sqlite3.h>
         ^
    1 error generated.


Looks like freebsd won't be an option for SQLbong.

Thanks for the help!

**Comment by sordina** [comment]
I will have a go at getting this to work on FreeBSD, so stay tuned :)

**Comment by sordina** [comment]
I've finally got round to having a look at this using Vagrant:

    [vagrant@vagrant-freebsd-10 ~/SQLBong]$ uname -a
    FreeBSD vagrant-freebsd-10 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

and got it to work by updating the Options variable in the Makefile:

    Options  = -lm -Wall -I /usr/local/include -L /usr/local/lib pcre_split.c sqlbong.c -lpcre -lsqlite3 -o sqlbong

Installing the following packages:

    sudo pkg install pcre
    sudo pkg install sqlite3

and building with make

    make

This generated the expected result:

    [vagrant@vagrant-freebsd-10 ~/SQLBong]$ (echo 1 2 3; echo 4 5 6) | ./sqlbong 'select d1.c1, d2.c1 from data d1, data d2'
    1 1
    1 4
    4 1
    4 4

I'll try to get the options supported in a standardised way, maybe with a configure script or something, until then, give this a go.

**Comment by jungle-boogie** [comment]
> give this a go.

Nice work! no problems with your steps above. I build sqlite3 from src/trunk and it works great with SQLBong.

I support standard options as it will work better for cross platforms.

**Comment by sordina** [comment]
ede47fb 

I've updated the default library and include directories to include /usr/local/lib and /usr/local/include. You can overwrite these by setting CLANG_OPTS during make.

For example:

    make CLANG_OPTS="-L /home/guest/includes"


I'll close this issue now :)

**Comment by jungle-boogie** [comment]
Hi @sordina,

Thanks for the assistance with this!

Just one small question...
I know make is making the binary in my local directory but how do I install it where my installed binaries are? usually I can use `sudo make install` and it will `cp file to /usr/local/bin/`

    % sudo make install
    make: don't know how to make install. Stop

    make: stopped in /usr/home/sean/bin/SQLBong

**Comment by sordina** [comment]
I don't have an installation target at the moment, but I'll add one if you like.

For now just copy it:

    sudo cp sqlbong /usr/local/bin/

**Comment by jungle-boogie** [comment]
Yes, I think an install target is a great idea, but that's just my thoughts. I will cp the file until you decide. ;)

**Comment by sordina** [comment]
Done: d5f1067

**Comment by sordina** [comment]
Note, this doesn't use sudo, so you might have to do `sudo make install` if your user can't write to /usr/local/bin.

**Comment by jungle-boogie** [comment]
:+1:  :+1:

**Comment by jungle-boogie** [comment]
hmmm....

Trying this on a different machine (that already has pcre & sqlite3) I get this with a simple make:

    % make
    echo "#ifndef USAGEH"                                                             > usage.h
    echo "#define USAGEH"                                                            >> usage.h
    echo "void usage() {"                                                            >> usage.h
    cat README.md | sed 's/["%\\]/\\&/g;s/^/printf("/;s/$/\\n");/' | grep -v '<img' >> usage.h
    echo "}"                                                                         >> usage.h
    echo "#endif"                                                                    >> usage.h
    clang -I /usr/local/include -L /usr/local/lib -lm -Wall pcre_split.c sqlbong.c -lpcre -lsqlite3 -o sqlbong
    clang: error: no such file or directory: 'pcre_split.c'
    *** Error code 1

    Stop.
    make: stopped in /home/sean/bin/SQLBong

**Comment by jungle-boogie** [comment]
Hi @sordina,

On a brand new freebsd VM (not vagrant), I get the same message above. So whatever hackery we previously did gave us a false positive that SQLBong installed correctly.

**Comment by sordina** [comment]
hmm...

**Comment by sordina** [comment]
Fixed in 17e7e377..738623c

Looks like pcre_split wasn't being initialized.

**Comment by jungle-boogie** [comment]
another pair of thumbs up. great work. :+1: :+1:
