### ISSUE TITLE
Make releases?

### ISSUE THREAD

**Issue by jungle-boogie** [sordina/SQLBong#7]
Hello,

I'd like to port your utility to FreeBSD ports/pkgs but you don't have any releases. Are you planning on maintaining SQLBong and/or would you make any releases on a regular basis?

Thanks!

**Comment by sordina** [comment]
Hi Jungle-Boogie,

I'm happy to add support for it if it's not too much trouble.
I'm planning on maintaining SQLBong, as I use it fairly regularly.
What release process are you referring to? Let me know what I can do to get it started, and I'll look into kicking it off :)

**Comment by jungle-boogie** [comment]
Hi @sordina,

No, no extra work on your part. You will just need to tag a version and I guess it will show up as a release in github: https://github.com/sordina/SQLBong/releases

see also:
http://git-scm.com/book/en/v2/Git-Basics-Tagging

The reason for this is so package maintainers (like I would be with SQLBong) know you've made a new release and it can be pulled in and upgraded on people's OS'.

The reason I ask about maintaining is to see if you would add new features/fix things and tag a new release. If you're happy with the way SQLBong works now, there probably won't be a need to make a tag and/or release.

Hope this helps!

**Comment by sordina** [comment]
Oh thanks!

I didn't realise that Github treated tags as releases.

I've pushed up the first one now: `git tag -a v0.1 -m "Tentative First Release"`

Let me know if there's something else required :)

**Comment by jungle-boogie** [comment]
Perfect, nice work.

Do you have a license for SQLBong?

**Comment by sordina** [comment]
Good question. I usually favour something like MIT, but I'm inclined to follow SQLite's lead on this, since I basically just leverage their library. It seems that the project is [Public Domain](https://www.sqlite.org/copyright.html). Is that going to cause problems?

**Comment by jungle-boogie** [comment]
>  Is that going to cause problems?

No, not at all. Just that I can list it with the project. see: https://www.freshports.org/databases/sqlite3

**Comment by sordina** [comment]
I think I'll just attach the MIT license for now, as I don't fully understand what's required to make my code public domain, as the SQLite licence references signing affidavits, etc.

**Comment by sordina** [comment]
Does that mean a new release post-license is required?

**Comment by sordina** [comment]
Added tag 0.1.1

Can I close the issue?

**Comment by jungle-boogie** [comment]
> Can I close the issue?

Sure, but I'm creating a second one about the build problem.

**Comment by sordina** [comment]
Looking forward to hearing about the build problem.

**Comment by sordina** [comment]
@jungle-boogie do you have any more info on the build problem?

**Comment by jungle-boogie** [comment]
Sorry for the delays with this.

The build problems are my misunderstandings of git submodules:
https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/makefile-distfiles.html#makefile-master_sites-github-multi

**Comment by sordina** [comment]
Ah, I see.

Thanks for the clarification :)
